// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.15.8
// source: sessionService.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SessionService_RegisterClient_FullMethodName           = "/proto.SessionService/RegisterClient"
	SessionService_UnRegisterClient_FullMethodName         = "/proto.SessionService/UnRegisterClient"
	SessionService_GetWSHandlerWithClientID_FullMethodName = "/proto.SessionService/GetWSHandlerWithClientID"
)

// SessionServiceClient is the client API for SessionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SessionServiceClient interface {
	RegisterClient(ctx context.Context, in *RegisterClientRequest, opts ...grpc.CallOption) (*RegisterClientResponse, error)
	UnRegisterClient(ctx context.Context, in *UnRegisterClientRequest, opts ...grpc.CallOption) (*UnRegisterClientResponse, error)
	GetWSHandlerWithClientID(ctx context.Context, in *GetWSHandlerWithClientIDsRequest, opts ...grpc.CallOption) (*GetWSHandlerWithClientIDsResponse, error)
}

type sessionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSessionServiceClient(cc grpc.ClientConnInterface) SessionServiceClient {
	return &sessionServiceClient{cc}
}

func (c *sessionServiceClient) RegisterClient(ctx context.Context, in *RegisterClientRequest, opts ...grpc.CallOption) (*RegisterClientResponse, error) {
	out := new(RegisterClientResponse)
	err := c.cc.Invoke(ctx, SessionService_RegisterClient_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) UnRegisterClient(ctx context.Context, in *UnRegisterClientRequest, opts ...grpc.CallOption) (*UnRegisterClientResponse, error) {
	out := new(UnRegisterClientResponse)
	err := c.cc.Invoke(ctx, SessionService_UnRegisterClient_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) GetWSHandlerWithClientID(ctx context.Context, in *GetWSHandlerWithClientIDsRequest, opts ...grpc.CallOption) (*GetWSHandlerWithClientIDsResponse, error) {
	out := new(GetWSHandlerWithClientIDsResponse)
	err := c.cc.Invoke(ctx, SessionService_GetWSHandlerWithClientID_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SessionServiceServer is the server API for SessionService service.
// All implementations must embed UnimplementedSessionServiceServer
// for forward compatibility
type SessionServiceServer interface {
	RegisterClient(context.Context, *RegisterClientRequest) (*RegisterClientResponse, error)
	UnRegisterClient(context.Context, *UnRegisterClientRequest) (*UnRegisterClientResponse, error)
	GetWSHandlerWithClientID(context.Context, *GetWSHandlerWithClientIDsRequest) (*GetWSHandlerWithClientIDsResponse, error)
	mustEmbedUnimplementedSessionServiceServer()
}

// UnimplementedSessionServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSessionServiceServer struct {
}

func (UnimplementedSessionServiceServer) RegisterClient(context.Context, *RegisterClientRequest) (*RegisterClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterClient not implemented")
}
func (UnimplementedSessionServiceServer) UnRegisterClient(context.Context, *UnRegisterClientRequest) (*UnRegisterClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnRegisterClient not implemented")
}
func (UnimplementedSessionServiceServer) GetWSHandlerWithClientID(context.Context, *GetWSHandlerWithClientIDsRequest) (*GetWSHandlerWithClientIDsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWSHandlerWithClientID not implemented")
}
func (UnimplementedSessionServiceServer) mustEmbedUnimplementedSessionServiceServer() {}

// UnsafeSessionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SessionServiceServer will
// result in compilation errors.
type UnsafeSessionServiceServer interface {
	mustEmbedUnimplementedSessionServiceServer()
}

func RegisterSessionServiceServer(s grpc.ServiceRegistrar, srv SessionServiceServer) {
	s.RegisterService(&SessionService_ServiceDesc, srv)
}

func _SessionService_RegisterClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).RegisterClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_RegisterClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).RegisterClient(ctx, req.(*RegisterClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_UnRegisterClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnRegisterClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).UnRegisterClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_UnRegisterClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).UnRegisterClient(ctx, req.(*UnRegisterClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_GetWSHandlerWithClientID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWSHandlerWithClientIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).GetWSHandlerWithClientID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_GetWSHandlerWithClientID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).GetWSHandlerWithClientID(ctx, req.(*GetWSHandlerWithClientIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SessionService_ServiceDesc is the grpc.ServiceDesc for SessionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SessionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.SessionService",
	HandlerType: (*SessionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterClient",
			Handler:    _SessionService_RegisterClient_Handler,
		},
		{
			MethodName: "UnRegisterClient",
			Handler:    _SessionService_UnRegisterClient_Handler,
		},
		{
			MethodName: "GetWSHandlerWithClientID",
			Handler:    _SessionService_GetWSHandlerWithClientID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sessionService.proto",
}
